# On utilise une image PHP officielle avec l'extension de votre choix (ou une image configurée)
image: php:8.4-cli

# Définition des dossiers à mettre en cache entre les étapes pour gagner du temps
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - vendor/

# L'ordre d'exécution de nos tâches
stages:
  - build
  - lint
  - test

# 1️⃣ ÉTAPE BUILD : Installation des dépendances
install_dependencies:
  stage: build
  before_script:
    # Installation de unzip nécessaire pour Composer
    - apt-get update && apt-get install -y unzip libicu-dev
    # 2. Configuration et installation de l'extension PHP intl
    - docker-php-ext-configure intl
    - docker-php-ext-install intl
    # 3. Installation de Composer
    - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  script:
    - composer install --no-progress --no-suggest --prefer-dist
  artifacts:
    paths:
      - vendor/
    expire_in: 1 hr

# 2️⃣ ÉTAPE LINT : Analyse statique avec PHPStan au Niveau 9
phpstan:
  stage: lint
  script:
    - vendor/bin/phpstan analyse src tests --level=9

twig_lint:
  stage: lint
  script:
    - php bin/console lint:twig templates

# 3️⃣ ÉTAPE TEST : Exécution de PHPUnit et couverture
phpunit:
  stage: test
  services:
    - name: mysql:8.0
      alias: db_test
  # 💡 On configure les variables d'environnement pour l'application et pour MySQL
  variables:
    MYSQL_USER: root
    MYSQL_PASSWORD: ""
    MYSQL_ROOT_PASSWORD: ""
    MYSQL_DATABASE: critipixel_test
    # On dit à Symfony de se connecter au service "db_test" configuré juste au-dessus
    DATABASE_URL: "mysql://root:@db_test:3306/criti-pixel_test?serverVersion=8.0.32&charset=utf8mb4"
    APP_ENV: test
  dependencies:
    - install_dependencies
  before_script:
    # On installe et active l'extension Xdebug ou PCOV dans le conteneur pour la couverture
    - pecl install pcov && docker-php-ext-enable pcov
    - apt-get update && apt-get install -y libpq-dev
    - docker-php-ext-install pdo_mysql
    - pecl install pcov && docker-php-ext-enable pcov
    
    # 2. Préparation de la base de données de test (on crée le schéma et on charge les fixtures)
    - php bin/console doctrine:database:drop --force --if-exists --env=test
    - php bin/console doctrine:database:create --if-not-exists --env=test
    - php bin/console doctrine:schema:update --force --env=test
    - php bin/console doctrine:fixtures:load --no-interaction --env=test
  script:
    # On configure les variables d'environnement pour le test
    - export APP_ENV=test
    # On lance tes 22 tests
    - php bin/phpunit --coverage-text --colors=never
  allow_failure: false